flaskblog/models.py
#-*- coding: utf-8 -*-

from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, \
     check_password_hash


db=SQLAlchemy()

class User(db.Model):
     __tablename__ = 'users'
     id = db.Column(db.String(45),primary_key=True)
     username = db.Column(db.String(255),unique=True)
     password = db.Column(db.String(255))
     posts = db.relationship(
          'Post',backref='users',lazy='dynamic')

     def __init__(self,id,username,password):
          self.id = id
          self.username = username
          self.password = password


     def __repr__(self):
          return '<Model User "{}">' .format(self.name)


###添加多对多关系的关联表posts_tags
posts_tags = db.Table('posts_tags',
    db.Column('post_id', db.String(45), db.ForeignKey('posts.id')),
    db.Column('tag_id', db.String(45), db.ForeignKey('tags.id')))

class Post(db.Model):
     """Represents Proected posts."""
     __tablename__ = 'posts'
     id = db.Column(db.String(45),primary_key=True)
     title = db.Column(db.String(255))
     text = db.Column(db.Text())
     publish_date = db.Column(db.DateTime)
     user_id = db.Column(db.String(45),db.ForeignKey('users.id'))
     comments = db.relationship(
          'Comment',backref='posts',lazy='dynamic'
     )
     tags = db.relationship(
          'Tag',secondary=posts_tags,backref=db.backref('posts',lazy='dynamic'))

     def __init__(self,id,title):
         self.id = id
         self.title = title

     def __repr__(self):
          return "<Model Post '{}'>".format(self.title)

class Comment(db.Model):
     """Represents Proected comments."""
     __tablename__='comments'
     id = db.Column(db.String(45),primary_key=True)
     name = db.Column(db.String(255))
     text = db.Column(db.Text())
     date = db.Column(db.DateTime())
     post_id = db.Column(db.String(45),db.ForeignKey('posts.id'))

     def __init__(self,id,name):
          self.id = id
          self.name = name

     def __repr__(self):
          return "<Model Comment '{}'>".format(self.name)

class Tag(db.Model):
     """Trpresents Proected tags."""
     __tablename__ = 'tags'
     id = db.Column(db.String(45),primary_key=True)
     name = db.Column(db.String(255))

     def __init__(self,id,name):
          self.id = id
          self.name = name

     def __repr__(self):
          return "<Model Tag '{}'>".format(self.name)

flaskblog/__init__.py
from flask import Flask, redirect, url_for

from models import db
from controllers import blog

def create_app(object_name):
    """Create the app instance via `Factory Method`"""

    app = Flask(__name__)
    # Set the app config
    app.config.from_object(object_name)

    # Will be load the SQLALCHEMY_DATABASE_URL from config.py to db object
    db.init_app(app)

    @app.route('/')
    def index():
        # Redirect the Request_url '/' to '/blog/'
        return redirect(url_for('blog.home'))

    # Register the Blueprint into app object
    app.register_blueprint(blog.blog_blueprint)

    return app

flaskblog/controllers/blog.py
#-*- coding: utf-8 -*-
from uuid import uuid4
from os import path
from datetime import datetime
from flask import render_template, Blueprint
from sqlalchemy import func
from flaskblog.models import db, User, Post, Tag, Comment, posts_tags
from flaskblog.froms import CommentForm



blog_blueprint = Blueprint(
    'blog',
    __name__,
    # path.pardir ==> ..
    template_folder=path.join(path.pardir, 'templates', 'blog'),
    # Prefix of Route URL
    url_prefix='/blog')


def sidebar_data():
    """Set the sidebar function."""
    recent = db.session.query(Post).order_by(
        Post.publish_date.desc()
    ).limit(5).all()

    top_tags = db.session.query(
        Tag, func.count(posts_tags.c.post_id).label('total')
    ).join(
        posts_tags
    ).group_by(Tag).order_by('total DESC').limit(5).all()
    return recent, top_tags

@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>',methods=['GET','POST'])
def home(page=1):
    """View function for home page"""

    posts = Post.query.order_by(
        Post.publish_date.desc()
    ).paginate(page, 10)

    recent, top_tags = sidebar_data()

    return render_template('blog/home.html',
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/post/<string:post_id>', methods=('GET', 'POST'))
def post(post_id):
    """View function for post page"""

    # Form object: `Comment`
    form = CommentForm()
    # form.validate_on_submit() will be true and return the
    # data object to form instance from user enter,
    # when the HTTP request is POST
    if form.validate_on_submit():
        new_comment = Comment(id=str(uuid4()),
                              name=form.name.data)
        new_comment.text = form.text.data
        new_comment.date = datetime.datetime.now()
        new_comment.post_id = post_id
        db.session.add(new_comment)
        db.session.commit()

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template('blog/post.html',
                           post=post,
                           tags=tags,
                           comments=comments,
                           form=form,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/tag/<string:tag_name>')
def tag(tag_name,page=1):
    """View function for tag page"""

    tag = db.session.query(Tag).filter_by(name=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_date.desc()).paginate(page, 10)
    recent, top_tags = sidebar_data()

    return render_template('blog/tag.html',
                           tag=tag,
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/user/<string:username>')
def user(username):
    """View function for user page"""
    user = db.session.query(User).filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.publish_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template('blog/user.html',
                           user=user,
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)

# @blog_blueprint.route('/user/<name>')
# def user(name):
#     return render_template('user.html', name=name)

@blog_blueprint.errorhandler(404)
def page_not_found(e):
    return render_template('blog/404.html'), 404

@blog_blueprint.errorhandler(500)
def internal_server_error(e):
    return render_template('blog/500.html'), 500

flaskblog/templates/blog/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,, initial-scale=1">
    <!-- Will be replace the page title -->
    <title>{% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- Macro: `render paginate` -->
    {% macro render_pagination(pagination, endpoint) %}
        <nav>
            <ul class="pagination">
                <li>
                    {% if pagination.has_prev %}
                        <a href="{{ url_for('blog.home', page=pagination.prev().page)
                                }}" aria-label="Previous">
                    {% else %}
                        <a href="{{ url_for('blog.home', page=1) }}" aria-label="Previous">
                    {% endif %}
                    <span aria-label="true">&laquo;</span>
                    </a>
                </li>
                {% for page in pagination.iter_pages() %}
                    {% if page %}
                        {% if page != pagination.page %}
                            <li>
                                <a href="{{ url_for(endpoint, page=page) }}">
                                    {{ page }}
                                </a>
                            </li>
                        {% else %}
                            <li><a href="">{{ page }}</a></li>
                        {% endif %}
                    {% else %}
                        <li><a>.........</a></li>
                    {% endif %}
                {% endfor %}
                <li>
                    <a href="{{ url_for('blog.home', page=pagination.next().page )
                            }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                <li>
            </ul>
        </nav>
    {% endmacro %}
</head>
<body>

<div class="container">
    <div class="jumbotron">
        <!-- Replace the route function to URL: `/` -->
        <h1><a href="{{ url_for('blog.home')}} ">蜷缩的蜗牛</a></h1>
        <p>Welcome to the blog!</p>
    </div>
    {% block body %}
        body_content
    {% endblock %}

</div>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</body>
</html>

flaskblog/templates/blog/home.html
<!-- Replace the TITLE of template base.html -->
{% extends "blog/base.html" %}
{% block title %}蜷缩的蜗牛{% endblock %}

<!-- Replace the BODY of template base.html -->
{% block body %}
<!-- The data object from view function: `home()` -->
<div class="row">
    <div class="col-lg-9">
    <!-- Get Pagination object-->
        {% for post in posts.items %}
            <div class="row">
                <div class="col-lg-9">
                    <h1>{{ post.title }}</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-9">
                    {{ post.text | truncate(255) | safe }}
                    <!-- Set the link for read more -->
                    <a href="{{ url_for('blog.post', post_id=post.id) }}">Read More</a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="col-lg-3">
        <div class="row">
            <h5>最新发布文章</h5>
            <ul>
                {% for post in recent %}
                    <!-- Set the link for recent posts. -->
                    <li>
                        <a href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="row">
            <h5>标签</h5>
            <ul>
                {% for tag in top_tags %}
                    <li>
                        <a href="{{ url_for('blog.tag', tag_name=tag[0].name) }}">{{ tag[0].name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
  <!-- Call the Macro: `render_pagination` from base.html -->
  {{ render_pagination(posts, 'blog.home') }}
</div>
{% endblock %}

flaskblog/templates/blog/index.html
{% extends "blog/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Index{% endblock %}
{% block head %}
    {{ super() }}
    <style>

    </style>
{% endblock %}
{% block body %}
     {{ super() }}
 {{ moment.include_moment() }}
    <h1>Hello, World!</h1>
    <div style="width: 180px">
        {{ wtf.quick_form(form) }}
    </div>

    <p>The local date and time is {{ moment(current_time).format('LLL') }}.</p>
    <p>That was {{ moment(current_time).fromNow(refresh=True) }}</p>

    <p>现在时间时: {{ moment().format('YYYY年M月D日, h:mm:ss a') }}.</p>
<p>已经过去了: {{ moment().fromTime(current_time) }}.</p>
<p>{{ moment().calendar() }}.</p>
{% endblock %}

flaskblog/templates/blog/post.html
{% extends "blog/base.html" %}
{% block title %}{{ post.name }}{% endblock %}

<!-- Replace the BODY of template base.html -->
{% block body %}
    <p id="len"></p>
<h3>{{ post.title }}</h3>
{{ post.publish_date }}:
 <p id="l" >{{ post.text }}</p>

<div class="col-lg-12">
    <h3>New Comment:</h3>
    <!-- Set the form -->
    <form method="POST" action="{{ url_for('blog.post', post_id=post.id) }}">
        {{ form.hidden_tag() }}
        <div>
            <!-- Field: `name` label -->
            {{ form.name.label }}
            {% if form.name.errors %}
                {% for e in form.name.errors %}
                    <p class="help-block">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.name(class_="form-control") }}
        </div>
        <div class="form-group">
            {{ form.text.label }}
            {% if form.text.errors %}
                {% for e in form.text.errors %}
                    <p class="help-block">{{ e }}</p>
                {% endfor %}
            {% endif %}
            {{ form.text(class_='form-control') }}
        </div>
        <input class="btn btn-primary" type="submit" value="Add Comment">
    </form>
</div>

    <script src="/flaskblog/static/js/jquery.min.js"></script>
    <script type="application/javascript">

        $(document).ready(function(){
{#            var a = $("#l").text();#}
            var a =$("#l").text().replace(/[\r\n]/g,"<br/>");
            $("#l").html(a);
        });
    </script>
{% endblock %}

flaskblog/templates/blog/tag.html
{% extends "blog/home.html" %}
{% block title %}{{ tag.name }}{% endblock %}

<!-- Replace the BODY of template base.html -->
{% block body %}
    <h3><a href="{{ url_for('blog.tag', tag_name=tag.name) }}">{{ tag.name }}</a></h3>
    <div class="row">
        <div class="col-lg-9">
            {% for post in posts.items %}
                <div class="row">
                    <div class="col-lg-12">
                        <h1>{{ post.title }}</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        {{ post.text | truncate(255) | safe }}
                        <!-- Set the link for read more -->
                        <a href="{{ url_for('blog.post', post_id=post.id) }}">Read More</a>
                    </div>
                </div>
            {% endfor %}
            {{ render_pagination(posts, 'blog.home') }}
        </div>
        <div class="col-lg-3">
            <div class="row">
                <h5>Recent Posts</h5>
                <ul>
                    {% for post in recent %}
                        <!-- Set the link for recent posts. -->
                        <li>
                            <a href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="row">
                <h5>Popular Tags</h5>
                <ul>
                    {% for tag in top_tags %}
                        <li>
                            <a href="{{ url_for('blog.tag', tag_name=tag[0].name) }}">{{ tag[0].name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
  <!-- Call the Macro: `render_pagination` from base.html -->
    </div>
{% endblock %}

flaskblog/templates/blog/user.html
{% extends "blog/base.html" %}
{% block title %}Flasky{% endblock %}
{% block page_content %}
<div class="page-header">
<h1>Hello, {{ name }}!</h1>
</div>
{% endblock %}